title: Sulton Nizomiddin
author: Sulton Nizomiddin
description: Dasturlash va kitoblar haqida shaxsiy blog

url: "https://sulton43.github.io"
baseurl: ""

theme: minima

collections:
  reads:
    output: true
    permalink: /reads/:path/


plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
